package com.cn.count.dao;

import com.cn.count.model.SysParams;
import com.gitee.fastmybatis.core.mapper.CrudMapper;
import org.mapstruct.Mapper;


import java.util.List;


public interface SysParamsMapper extends CrudMapper<SysParams, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbg.generated
     */
    int insert(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbg.generated
     */
    List<SysParams> selectAll();
}