package com.cn.count.dao;

import com.cn.count.model.TabelTree;
import java.util.List;
import java.util.Map;

public interface TabelTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabel_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabel_tree
     *
     * @mbg.generated
     */
    int insert(TabelTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabel_tree
     *
     * @mbg.generated
     */
    TabelTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabel_tree
     *
     * @mbg.generated
     */
    List<TabelTree> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabel_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TabelTree record);

    List<TabelTree> selectAllLevelOne(int level);

    List<Map<String ,Object>>  getTableByName(String tabelName);
}