package com.cn.count.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CwrProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.eaf_id
     *
     * @mbg.generated
     */
    private String eafId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.eaf_creator
     *
     * @mbg.generated
     */
    private String eafCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.eaf_modifytime
     *
     * @mbg.generated
     */
    private Date eafModifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.eaf_createtime
     *
     * @mbg.generated
     */
    private Date eafCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.eaf_modifier
     *
     * @mbg.generated
     */
    private String eafModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_name
     *
     * @mbg.generated
     */
    private String cwrPrjName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_jian
     *
     * @mbg.generated
     */
    private String cwrPrjJian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_man
     *
     * @mbg.generated
     */
    private String cwrPrjMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_des
     *
     * @mbg.generated
     */
    private String cwrPrjDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_addr
     *
     * @mbg.generated
     */
    private String cwrPrjAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_status
     *
     * @mbg.generated
     */
    private String cwrPrjStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_org_name
     *
     * @mbg.generated
     */
    private String cwrOrgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_org_jian
     *
     * @mbg.generated
     */
    private String cwrOrgJian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_dir
     *
     * @mbg.generated
     */
    private String cwrPrjDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_cost_eng
     *
     * @mbg.generated
     */
    private String cwrCostEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_pre_eng
     *
     * @mbg.generated
     */
    private String cwrPreEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_pro_eng
     *
     * @mbg.generated
     */
    private String cwrProEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_fgpf_code
     *
     * @mbg.generated
     */
    private String cwrFgpfCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_type
     *
     * @mbg.generated
     */
    private String cwrPrjType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_rec_year
     *
     * @mbg.generated
     */
    private String cwrRecYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_maj_cat
     *
     * @mbg.generated
     */
    private String cwrMajCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_total_area
     *
     * @mbg.generated
     */
    private String cwrTotalArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_kspf_lx
     *
     * @mbg.generated
     */
    private String cwrKspfLx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_gspf_dy
     *
     * @mbg.generated
     */
    private String cwrGspfDy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_pfgs_tz
     *
     * @mbg.generated
     */
    private String cwrPfgsTz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_app_code
     *
     * @mbg.generated
     */
    private String cwrAppCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_gcghxk_code
     *
     * @mbg.generated
     */
    private String cwrGcghxkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_ydghxk_code
     *
     * @mbg.generated
     */
    private String cwrYdghxkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_xzyjs_code
     *
     * @mbg.generated
     */
    private String cwrXzyjsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_con_code
     *
     * @mbg.generated
     */
    private String cwrConCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_start_date
     *
     * @mbg.generated
     */
    private Date cwrStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_stage
     *
     * @mbg.generated
     */
    private String cwrPrjStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_code
     *
     * @mbg.generated
     */
    private String cwrPrjCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_use_com
     *
     * @mbg.generated
     */
    private String cwrUseCom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_cap_from
     *
     * @mbg.generated
     */
    private String cwrCapFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_sup_unit
     *
     * @mbg.generated
     */
    private String cwrSupUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_view
     *
     * @mbg.generated
     */
    private String cwrPrjView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_jdbh
     *
     * @mbg.generated
     */
    private String cwrJdbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_area
     *
     * @mbg.generated
     */
    private String cwrPrjArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_photo
     *
     * @mbg.generated
     */
    private String cwrPrjPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_addr_jd
     *
     * @mbg.generated
     */
    private String cwrAddrJd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_addr_wd
     *
     * @mbg.generated
     */
    private String cwrAddrWd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_isvproj
     *
     * @mbg.generated
     */
    private String cwrIsvproj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_sg_unit
     *
     * @mbg.generated
     */
    private String cwrSgUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_gcbh
     *
     * @mbg.generated
     */
    private String cwrPrjGcbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_islinked
     *
     * @mbg.generated
     */
    private String cwrPrjIslinked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_issalary
     *
     * @mbg.generated
     */
    private String cwrPrjIssalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_js_unit
     *
     * @mbg.generated
     */
    private String cwrJsUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_linked_date
     *
     * @mbg.generated
     */
    private Date cwrLinkedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_salary_date
     *
     * @mbg.generated
     */
    private Date cwrSalaryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_storage_gold
     *
     * @mbg.generated
     */
    private BigDecimal cwrStorageGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_control_unit
     *
     * @mbg.generated
     */
    private String cwrControlUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_design_unit
     *
     * @mbg.generated
     */
    private String cwrDesignUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_quality_unit
     *
     * @mbg.generated
     */
    private String cwrQualityUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_safety_unit
     *
     * @mbg.generated
     */
    private String cwrSafetyUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_pa_addr
     *
     * @mbg.generated
     */
    private String cwrPaAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_isbegin
     *
     * @mbg.generated
     */
    private String cwrPrjIsbegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_engin_name
     *
     * @mbg.generated
     */
    private String cwrEnginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_engin_addr
     *
     * @mbg.generated
     */
    private String cwrEnginAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_iscity
     *
     * @mbg.generated
     */
    private String cwrPrjIscity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_istown
     *
     * @mbg.generated
     */
    private String cwrPrjIstown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_red_area
     *
     * @mbg.generated
     */
    private BigDecimal cwrRedArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prj_scan
     *
     * @mbg.generated
     */
    private String cwrPrjScan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_subject_id
     *
     * @mbg.generated
     */
    private String cwrSubjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_subject_code
     *
     * @mbg.generated
     */
    private String cwrSubjectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_supervisor
     *
     * @mbg.generated
     */
    private String cwrSupervisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_supv_group
     *
     * @mbg.generated
     */
    private String cwrSupvGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_prv_prj_code
     *
     * @mbg.generated
     */
    private String cwrPrvPrjCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_sg_comid
     *
     * @mbg.generated
     */
    private String cwrSgComid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cwr_project.cwr_cmpl_date
     *
     * @mbg.generated
     */
    private Date cwrCmplDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cwr_project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.eaf_id
     *
     * @return the value of cwr_project.eaf_id
     *
     * @mbg.generated
     */
    public String getEafId() {
        return eafId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.eaf_id
     *
     * @param eafId the value for cwr_project.eaf_id
     *
     * @mbg.generated
     */
    public void setEafId(String eafId) {
        this.eafId = eafId == null ? null : eafId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.eaf_creator
     *
     * @return the value of cwr_project.eaf_creator
     *
     * @mbg.generated
     */
    public String getEafCreator() {
        return eafCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.eaf_creator
     *
     * @param eafCreator the value for cwr_project.eaf_creator
     *
     * @mbg.generated
     */
    public void setEafCreator(String eafCreator) {
        this.eafCreator = eafCreator == null ? null : eafCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.eaf_modifytime
     *
     * @return the value of cwr_project.eaf_modifytime
     *
     * @mbg.generated
     */
    public Date getEafModifytime() {
        return eafModifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.eaf_modifytime
     *
     * @param eafModifytime the value for cwr_project.eaf_modifytime
     *
     * @mbg.generated
     */
    public void setEafModifytime(Date eafModifytime) {
        this.eafModifytime = eafModifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.eaf_createtime
     *
     * @return the value of cwr_project.eaf_createtime
     *
     * @mbg.generated
     */
    public Date getEafCreatetime() {
        return eafCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.eaf_createtime
     *
     * @param eafCreatetime the value for cwr_project.eaf_createtime
     *
     * @mbg.generated
     */
    public void setEafCreatetime(Date eafCreatetime) {
        this.eafCreatetime = eafCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.eaf_modifier
     *
     * @return the value of cwr_project.eaf_modifier
     *
     * @mbg.generated
     */
    public String getEafModifier() {
        return eafModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.eaf_modifier
     *
     * @param eafModifier the value for cwr_project.eaf_modifier
     *
     * @mbg.generated
     */
    public void setEafModifier(String eafModifier) {
        this.eafModifier = eafModifier == null ? null : eafModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_name
     *
     * @return the value of cwr_project.cwr_prj_name
     *
     * @mbg.generated
     */
    public String getCwrPrjName() {
        return cwrPrjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_name
     *
     * @param cwrPrjName the value for cwr_project.cwr_prj_name
     *
     * @mbg.generated
     */
    public void setCwrPrjName(String cwrPrjName) {
        this.cwrPrjName = cwrPrjName == null ? null : cwrPrjName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_jian
     *
     * @return the value of cwr_project.cwr_prj_jian
     *
     * @mbg.generated
     */
    public String getCwrPrjJian() {
        return cwrPrjJian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_jian
     *
     * @param cwrPrjJian the value for cwr_project.cwr_prj_jian
     *
     * @mbg.generated
     */
    public void setCwrPrjJian(String cwrPrjJian) {
        this.cwrPrjJian = cwrPrjJian == null ? null : cwrPrjJian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_man
     *
     * @return the value of cwr_project.cwr_prj_man
     *
     * @mbg.generated
     */
    public String getCwrPrjMan() {
        return cwrPrjMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_man
     *
     * @param cwrPrjMan the value for cwr_project.cwr_prj_man
     *
     * @mbg.generated
     */
    public void setCwrPrjMan(String cwrPrjMan) {
        this.cwrPrjMan = cwrPrjMan == null ? null : cwrPrjMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_des
     *
     * @return the value of cwr_project.cwr_prj_des
     *
     * @mbg.generated
     */
    public String getCwrPrjDes() {
        return cwrPrjDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_des
     *
     * @param cwrPrjDes the value for cwr_project.cwr_prj_des
     *
     * @mbg.generated
     */
    public void setCwrPrjDes(String cwrPrjDes) {
        this.cwrPrjDes = cwrPrjDes == null ? null : cwrPrjDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_addr
     *
     * @return the value of cwr_project.cwr_prj_addr
     *
     * @mbg.generated
     */
    public String getCwrPrjAddr() {
        return cwrPrjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_addr
     *
     * @param cwrPrjAddr the value for cwr_project.cwr_prj_addr
     *
     * @mbg.generated
     */
    public void setCwrPrjAddr(String cwrPrjAddr) {
        this.cwrPrjAddr = cwrPrjAddr == null ? null : cwrPrjAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_status
     *
     * @return the value of cwr_project.cwr_prj_status
     *
     * @mbg.generated
     */
    public String getCwrPrjStatus() {
        return cwrPrjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_status
     *
     * @param cwrPrjStatus the value for cwr_project.cwr_prj_status
     *
     * @mbg.generated
     */
    public void setCwrPrjStatus(String cwrPrjStatus) {
        this.cwrPrjStatus = cwrPrjStatus == null ? null : cwrPrjStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_org_name
     *
     * @return the value of cwr_project.cwr_org_name
     *
     * @mbg.generated
     */
    public String getCwrOrgName() {
        return cwrOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_org_name
     *
     * @param cwrOrgName the value for cwr_project.cwr_org_name
     *
     * @mbg.generated
     */
    public void setCwrOrgName(String cwrOrgName) {
        this.cwrOrgName = cwrOrgName == null ? null : cwrOrgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_org_jian
     *
     * @return the value of cwr_project.cwr_org_jian
     *
     * @mbg.generated
     */
    public String getCwrOrgJian() {
        return cwrOrgJian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_org_jian
     *
     * @param cwrOrgJian the value for cwr_project.cwr_org_jian
     *
     * @mbg.generated
     */
    public void setCwrOrgJian(String cwrOrgJian) {
        this.cwrOrgJian = cwrOrgJian == null ? null : cwrOrgJian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_dir
     *
     * @return the value of cwr_project.cwr_prj_dir
     *
     * @mbg.generated
     */
    public String getCwrPrjDir() {
        return cwrPrjDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_dir
     *
     * @param cwrPrjDir the value for cwr_project.cwr_prj_dir
     *
     * @mbg.generated
     */
    public void setCwrPrjDir(String cwrPrjDir) {
        this.cwrPrjDir = cwrPrjDir == null ? null : cwrPrjDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_cost_eng
     *
     * @return the value of cwr_project.cwr_cost_eng
     *
     * @mbg.generated
     */
    public String getCwrCostEng() {
        return cwrCostEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_cost_eng
     *
     * @param cwrCostEng the value for cwr_project.cwr_cost_eng
     *
     * @mbg.generated
     */
    public void setCwrCostEng(String cwrCostEng) {
        this.cwrCostEng = cwrCostEng == null ? null : cwrCostEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_pre_eng
     *
     * @return the value of cwr_project.cwr_pre_eng
     *
     * @mbg.generated
     */
    public String getCwrPreEng() {
        return cwrPreEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_pre_eng
     *
     * @param cwrPreEng the value for cwr_project.cwr_pre_eng
     *
     * @mbg.generated
     */
    public void setCwrPreEng(String cwrPreEng) {
        this.cwrPreEng = cwrPreEng == null ? null : cwrPreEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_pro_eng
     *
     * @return the value of cwr_project.cwr_pro_eng
     *
     * @mbg.generated
     */
    public String getCwrProEng() {
        return cwrProEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_pro_eng
     *
     * @param cwrProEng the value for cwr_project.cwr_pro_eng
     *
     * @mbg.generated
     */
    public void setCwrProEng(String cwrProEng) {
        this.cwrProEng = cwrProEng == null ? null : cwrProEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_fgpf_code
     *
     * @return the value of cwr_project.cwr_fgpf_code
     *
     * @mbg.generated
     */
    public String getCwrFgpfCode() {
        return cwrFgpfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_fgpf_code
     *
     * @param cwrFgpfCode the value for cwr_project.cwr_fgpf_code
     *
     * @mbg.generated
     */
    public void setCwrFgpfCode(String cwrFgpfCode) {
        this.cwrFgpfCode = cwrFgpfCode == null ? null : cwrFgpfCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_type
     *
     * @return the value of cwr_project.cwr_prj_type
     *
     * @mbg.generated
     */
    public String getCwrPrjType() {
        return cwrPrjType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_type
     *
     * @param cwrPrjType the value for cwr_project.cwr_prj_type
     *
     * @mbg.generated
     */
    public void setCwrPrjType(String cwrPrjType) {
        this.cwrPrjType = cwrPrjType == null ? null : cwrPrjType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_rec_year
     *
     * @return the value of cwr_project.cwr_rec_year
     *
     * @mbg.generated
     */
    public String getCwrRecYear() {
        return cwrRecYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_rec_year
     *
     * @param cwrRecYear the value for cwr_project.cwr_rec_year
     *
     * @mbg.generated
     */
    public void setCwrRecYear(String cwrRecYear) {
        this.cwrRecYear = cwrRecYear == null ? null : cwrRecYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_maj_cat
     *
     * @return the value of cwr_project.cwr_maj_cat
     *
     * @mbg.generated
     */
    public String getCwrMajCat() {
        return cwrMajCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_maj_cat
     *
     * @param cwrMajCat the value for cwr_project.cwr_maj_cat
     *
     * @mbg.generated
     */
    public void setCwrMajCat(String cwrMajCat) {
        this.cwrMajCat = cwrMajCat == null ? null : cwrMajCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_total_area
     *
     * @return the value of cwr_project.cwr_total_area
     *
     * @mbg.generated
     */
    public String getCwrTotalArea() {
        return cwrTotalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_total_area
     *
     * @param cwrTotalArea the value for cwr_project.cwr_total_area
     *
     * @mbg.generated
     */
    public void setCwrTotalArea(String cwrTotalArea) {
        this.cwrTotalArea = cwrTotalArea == null ? null : cwrTotalArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_kspf_lx
     *
     * @return the value of cwr_project.cwr_kspf_lx
     *
     * @mbg.generated
     */
    public String getCwrKspfLx() {
        return cwrKspfLx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_kspf_lx
     *
     * @param cwrKspfLx the value for cwr_project.cwr_kspf_lx
     *
     * @mbg.generated
     */
    public void setCwrKspfLx(String cwrKspfLx) {
        this.cwrKspfLx = cwrKspfLx == null ? null : cwrKspfLx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_gspf_dy
     *
     * @return the value of cwr_project.cwr_gspf_dy
     *
     * @mbg.generated
     */
    public String getCwrGspfDy() {
        return cwrGspfDy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_gspf_dy
     *
     * @param cwrGspfDy the value for cwr_project.cwr_gspf_dy
     *
     * @mbg.generated
     */
    public void setCwrGspfDy(String cwrGspfDy) {
        this.cwrGspfDy = cwrGspfDy == null ? null : cwrGspfDy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_pfgs_tz
     *
     * @return the value of cwr_project.cwr_pfgs_tz
     *
     * @mbg.generated
     */
    public String getCwrPfgsTz() {
        return cwrPfgsTz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_pfgs_tz
     *
     * @param cwrPfgsTz the value for cwr_project.cwr_pfgs_tz
     *
     * @mbg.generated
     */
    public void setCwrPfgsTz(String cwrPfgsTz) {
        this.cwrPfgsTz = cwrPfgsTz == null ? null : cwrPfgsTz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_app_code
     *
     * @return the value of cwr_project.cwr_app_code
     *
     * @mbg.generated
     */
    public String getCwrAppCode() {
        return cwrAppCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_app_code
     *
     * @param cwrAppCode the value for cwr_project.cwr_app_code
     *
     * @mbg.generated
     */
    public void setCwrAppCode(String cwrAppCode) {
        this.cwrAppCode = cwrAppCode == null ? null : cwrAppCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_gcghxk_code
     *
     * @return the value of cwr_project.cwr_gcghxk_code
     *
     * @mbg.generated
     */
    public String getCwrGcghxkCode() {
        return cwrGcghxkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_gcghxk_code
     *
     * @param cwrGcghxkCode the value for cwr_project.cwr_gcghxk_code
     *
     * @mbg.generated
     */
    public void setCwrGcghxkCode(String cwrGcghxkCode) {
        this.cwrGcghxkCode = cwrGcghxkCode == null ? null : cwrGcghxkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_ydghxk_code
     *
     * @return the value of cwr_project.cwr_ydghxk_code
     *
     * @mbg.generated
     */
    public String getCwrYdghxkCode() {
        return cwrYdghxkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_ydghxk_code
     *
     * @param cwrYdghxkCode the value for cwr_project.cwr_ydghxk_code
     *
     * @mbg.generated
     */
    public void setCwrYdghxkCode(String cwrYdghxkCode) {
        this.cwrYdghxkCode = cwrYdghxkCode == null ? null : cwrYdghxkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_xzyjs_code
     *
     * @return the value of cwr_project.cwr_xzyjs_code
     *
     * @mbg.generated
     */
    public String getCwrXzyjsCode() {
        return cwrXzyjsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_xzyjs_code
     *
     * @param cwrXzyjsCode the value for cwr_project.cwr_xzyjs_code
     *
     * @mbg.generated
     */
    public void setCwrXzyjsCode(String cwrXzyjsCode) {
        this.cwrXzyjsCode = cwrXzyjsCode == null ? null : cwrXzyjsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_con_code
     *
     * @return the value of cwr_project.cwr_con_code
     *
     * @mbg.generated
     */
    public String getCwrConCode() {
        return cwrConCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_con_code
     *
     * @param cwrConCode the value for cwr_project.cwr_con_code
     *
     * @mbg.generated
     */
    public void setCwrConCode(String cwrConCode) {
        this.cwrConCode = cwrConCode == null ? null : cwrConCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_start_date
     *
     * @return the value of cwr_project.cwr_start_date
     *
     * @mbg.generated
     */
    public Date getCwrStartDate() {
        return cwrStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_start_date
     *
     * @param cwrStartDate the value for cwr_project.cwr_start_date
     *
     * @mbg.generated
     */
    public void setCwrStartDate(Date cwrStartDate) {
        this.cwrStartDate = cwrStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_stage
     *
     * @return the value of cwr_project.cwr_prj_stage
     *
     * @mbg.generated
     */
    public String getCwrPrjStage() {
        return cwrPrjStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_stage
     *
     * @param cwrPrjStage the value for cwr_project.cwr_prj_stage
     *
     * @mbg.generated
     */
    public void setCwrPrjStage(String cwrPrjStage) {
        this.cwrPrjStage = cwrPrjStage == null ? null : cwrPrjStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_code
     *
     * @return the value of cwr_project.cwr_prj_code
     *
     * @mbg.generated
     */
    public String getCwrPrjCode() {
        return cwrPrjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_code
     *
     * @param cwrPrjCode the value for cwr_project.cwr_prj_code
     *
     * @mbg.generated
     */
    public void setCwrPrjCode(String cwrPrjCode) {
        this.cwrPrjCode = cwrPrjCode == null ? null : cwrPrjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_use_com
     *
     * @return the value of cwr_project.cwr_use_com
     *
     * @mbg.generated
     */
    public String getCwrUseCom() {
        return cwrUseCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_use_com
     *
     * @param cwrUseCom the value for cwr_project.cwr_use_com
     *
     * @mbg.generated
     */
    public void setCwrUseCom(String cwrUseCom) {
        this.cwrUseCom = cwrUseCom == null ? null : cwrUseCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_cap_from
     *
     * @return the value of cwr_project.cwr_cap_from
     *
     * @mbg.generated
     */
    public String getCwrCapFrom() {
        return cwrCapFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_cap_from
     *
     * @param cwrCapFrom the value for cwr_project.cwr_cap_from
     *
     * @mbg.generated
     */
    public void setCwrCapFrom(String cwrCapFrom) {
        this.cwrCapFrom = cwrCapFrom == null ? null : cwrCapFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_sup_unit
     *
     * @return the value of cwr_project.cwr_sup_unit
     *
     * @mbg.generated
     */
    public String getCwrSupUnit() {
        return cwrSupUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_sup_unit
     *
     * @param cwrSupUnit the value for cwr_project.cwr_sup_unit
     *
     * @mbg.generated
     */
    public void setCwrSupUnit(String cwrSupUnit) {
        this.cwrSupUnit = cwrSupUnit == null ? null : cwrSupUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_view
     *
     * @return the value of cwr_project.cwr_prj_view
     *
     * @mbg.generated
     */
    public String getCwrPrjView() {
        return cwrPrjView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_view
     *
     * @param cwrPrjView the value for cwr_project.cwr_prj_view
     *
     * @mbg.generated
     */
    public void setCwrPrjView(String cwrPrjView) {
        this.cwrPrjView = cwrPrjView == null ? null : cwrPrjView.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_jdbh
     *
     * @return the value of cwr_project.cwr_jdbh
     *
     * @mbg.generated
     */
    public String getCwrJdbh() {
        return cwrJdbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_jdbh
     *
     * @param cwrJdbh the value for cwr_project.cwr_jdbh
     *
     * @mbg.generated
     */
    public void setCwrJdbh(String cwrJdbh) {
        this.cwrJdbh = cwrJdbh == null ? null : cwrJdbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_area
     *
     * @return the value of cwr_project.cwr_prj_area
     *
     * @mbg.generated
     */
    public String getCwrPrjArea() {
        return cwrPrjArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_area
     *
     * @param cwrPrjArea the value for cwr_project.cwr_prj_area
     *
     * @mbg.generated
     */
    public void setCwrPrjArea(String cwrPrjArea) {
        this.cwrPrjArea = cwrPrjArea == null ? null : cwrPrjArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_photo
     *
     * @return the value of cwr_project.cwr_prj_photo
     *
     * @mbg.generated
     */
    public String getCwrPrjPhoto() {
        return cwrPrjPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_photo
     *
     * @param cwrPrjPhoto the value for cwr_project.cwr_prj_photo
     *
     * @mbg.generated
     */
    public void setCwrPrjPhoto(String cwrPrjPhoto) {
        this.cwrPrjPhoto = cwrPrjPhoto == null ? null : cwrPrjPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_addr_jd
     *
     * @return the value of cwr_project.cwr_addr_jd
     *
     * @mbg.generated
     */
    public String getCwrAddrJd() {
        return cwrAddrJd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_addr_jd
     *
     * @param cwrAddrJd the value for cwr_project.cwr_addr_jd
     *
     * @mbg.generated
     */
    public void setCwrAddrJd(String cwrAddrJd) {
        this.cwrAddrJd = cwrAddrJd == null ? null : cwrAddrJd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_addr_wd
     *
     * @return the value of cwr_project.cwr_addr_wd
     *
     * @mbg.generated
     */
    public String getCwrAddrWd() {
        return cwrAddrWd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_addr_wd
     *
     * @param cwrAddrWd the value for cwr_project.cwr_addr_wd
     *
     * @mbg.generated
     */
    public void setCwrAddrWd(String cwrAddrWd) {
        this.cwrAddrWd = cwrAddrWd == null ? null : cwrAddrWd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_isvproj
     *
     * @return the value of cwr_project.cwr_isvproj
     *
     * @mbg.generated
     */
    public String getCwrIsvproj() {
        return cwrIsvproj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_isvproj
     *
     * @param cwrIsvproj the value for cwr_project.cwr_isvproj
     *
     * @mbg.generated
     */
    public void setCwrIsvproj(String cwrIsvproj) {
        this.cwrIsvproj = cwrIsvproj == null ? null : cwrIsvproj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_sg_unit
     *
     * @return the value of cwr_project.cwr_sg_unit
     *
     * @mbg.generated
     */
    public String getCwrSgUnit() {
        return cwrSgUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_sg_unit
     *
     * @param cwrSgUnit the value for cwr_project.cwr_sg_unit
     *
     * @mbg.generated
     */
    public void setCwrSgUnit(String cwrSgUnit) {
        this.cwrSgUnit = cwrSgUnit == null ? null : cwrSgUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_gcbh
     *
     * @return the value of cwr_project.cwr_prj_gcbh
     *
     * @mbg.generated
     */
    public String getCwrPrjGcbh() {
        return cwrPrjGcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_gcbh
     *
     * @param cwrPrjGcbh the value for cwr_project.cwr_prj_gcbh
     *
     * @mbg.generated
     */
    public void setCwrPrjGcbh(String cwrPrjGcbh) {
        this.cwrPrjGcbh = cwrPrjGcbh == null ? null : cwrPrjGcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_islinked
     *
     * @return the value of cwr_project.cwr_prj_islinked
     *
     * @mbg.generated
     */
    public String getCwrPrjIslinked() {
        return cwrPrjIslinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_islinked
     *
     * @param cwrPrjIslinked the value for cwr_project.cwr_prj_islinked
     *
     * @mbg.generated
     */
    public void setCwrPrjIslinked(String cwrPrjIslinked) {
        this.cwrPrjIslinked = cwrPrjIslinked == null ? null : cwrPrjIslinked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_issalary
     *
     * @return the value of cwr_project.cwr_prj_issalary
     *
     * @mbg.generated
     */
    public String getCwrPrjIssalary() {
        return cwrPrjIssalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_issalary
     *
     * @param cwrPrjIssalary the value for cwr_project.cwr_prj_issalary
     *
     * @mbg.generated
     */
    public void setCwrPrjIssalary(String cwrPrjIssalary) {
        this.cwrPrjIssalary = cwrPrjIssalary == null ? null : cwrPrjIssalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_js_unit
     *
     * @return the value of cwr_project.cwr_js_unit
     *
     * @mbg.generated
     */
    public String getCwrJsUnit() {
        return cwrJsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_js_unit
     *
     * @param cwrJsUnit the value for cwr_project.cwr_js_unit
     *
     * @mbg.generated
     */
    public void setCwrJsUnit(String cwrJsUnit) {
        this.cwrJsUnit = cwrJsUnit == null ? null : cwrJsUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_linked_date
     *
     * @return the value of cwr_project.cwr_linked_date
     *
     * @mbg.generated
     */
    public Date getCwrLinkedDate() {
        return cwrLinkedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_linked_date
     *
     * @param cwrLinkedDate the value for cwr_project.cwr_linked_date
     *
     * @mbg.generated
     */
    public void setCwrLinkedDate(Date cwrLinkedDate) {
        this.cwrLinkedDate = cwrLinkedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_salary_date
     *
     * @return the value of cwr_project.cwr_salary_date
     *
     * @mbg.generated
     */
    public Date getCwrSalaryDate() {
        return cwrSalaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_salary_date
     *
     * @param cwrSalaryDate the value for cwr_project.cwr_salary_date
     *
     * @mbg.generated
     */
    public void setCwrSalaryDate(Date cwrSalaryDate) {
        this.cwrSalaryDate = cwrSalaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_storage_gold
     *
     * @return the value of cwr_project.cwr_storage_gold
     *
     * @mbg.generated
     */
    public BigDecimal getCwrStorageGold() {
        return cwrStorageGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_storage_gold
     *
     * @param cwrStorageGold the value for cwr_project.cwr_storage_gold
     *
     * @mbg.generated
     */
    public void setCwrStorageGold(BigDecimal cwrStorageGold) {
        this.cwrStorageGold = cwrStorageGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_control_unit
     *
     * @return the value of cwr_project.cwr_control_unit
     *
     * @mbg.generated
     */
    public String getCwrControlUnit() {
        return cwrControlUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_control_unit
     *
     * @param cwrControlUnit the value for cwr_project.cwr_control_unit
     *
     * @mbg.generated
     */
    public void setCwrControlUnit(String cwrControlUnit) {
        this.cwrControlUnit = cwrControlUnit == null ? null : cwrControlUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_design_unit
     *
     * @return the value of cwr_project.cwr_design_unit
     *
     * @mbg.generated
     */
    public String getCwrDesignUnit() {
        return cwrDesignUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_design_unit
     *
     * @param cwrDesignUnit the value for cwr_project.cwr_design_unit
     *
     * @mbg.generated
     */
    public void setCwrDesignUnit(String cwrDesignUnit) {
        this.cwrDesignUnit = cwrDesignUnit == null ? null : cwrDesignUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_quality_unit
     *
     * @return the value of cwr_project.cwr_quality_unit
     *
     * @mbg.generated
     */
    public String getCwrQualityUnit() {
        return cwrQualityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_quality_unit
     *
     * @param cwrQualityUnit the value for cwr_project.cwr_quality_unit
     *
     * @mbg.generated
     */
    public void setCwrQualityUnit(String cwrQualityUnit) {
        this.cwrQualityUnit = cwrQualityUnit == null ? null : cwrQualityUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_safety_unit
     *
     * @return the value of cwr_project.cwr_safety_unit
     *
     * @mbg.generated
     */
    public String getCwrSafetyUnit() {
        return cwrSafetyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_safety_unit
     *
     * @param cwrSafetyUnit the value for cwr_project.cwr_safety_unit
     *
     * @mbg.generated
     */
    public void setCwrSafetyUnit(String cwrSafetyUnit) {
        this.cwrSafetyUnit = cwrSafetyUnit == null ? null : cwrSafetyUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_pa_addr
     *
     * @return the value of cwr_project.cwr_pa_addr
     *
     * @mbg.generated
     */
    public String getCwrPaAddr() {
        return cwrPaAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_pa_addr
     *
     * @param cwrPaAddr the value for cwr_project.cwr_pa_addr
     *
     * @mbg.generated
     */
    public void setCwrPaAddr(String cwrPaAddr) {
        this.cwrPaAddr = cwrPaAddr == null ? null : cwrPaAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_isbegin
     *
     * @return the value of cwr_project.cwr_prj_isbegin
     *
     * @mbg.generated
     */
    public String getCwrPrjIsbegin() {
        return cwrPrjIsbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_isbegin
     *
     * @param cwrPrjIsbegin the value for cwr_project.cwr_prj_isbegin
     *
     * @mbg.generated
     */
    public void setCwrPrjIsbegin(String cwrPrjIsbegin) {
        this.cwrPrjIsbegin = cwrPrjIsbegin == null ? null : cwrPrjIsbegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_engin_name
     *
     * @return the value of cwr_project.cwr_engin_name
     *
     * @mbg.generated
     */
    public String getCwrEnginName() {
        return cwrEnginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_engin_name
     *
     * @param cwrEnginName the value for cwr_project.cwr_engin_name
     *
     * @mbg.generated
     */
    public void setCwrEnginName(String cwrEnginName) {
        this.cwrEnginName = cwrEnginName == null ? null : cwrEnginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_engin_addr
     *
     * @return the value of cwr_project.cwr_engin_addr
     *
     * @mbg.generated
     */
    public String getCwrEnginAddr() {
        return cwrEnginAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_engin_addr
     *
     * @param cwrEnginAddr the value for cwr_project.cwr_engin_addr
     *
     * @mbg.generated
     */
    public void setCwrEnginAddr(String cwrEnginAddr) {
        this.cwrEnginAddr = cwrEnginAddr == null ? null : cwrEnginAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_iscity
     *
     * @return the value of cwr_project.cwr_prj_iscity
     *
     * @mbg.generated
     */
    public String getCwrPrjIscity() {
        return cwrPrjIscity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_iscity
     *
     * @param cwrPrjIscity the value for cwr_project.cwr_prj_iscity
     *
     * @mbg.generated
     */
    public void setCwrPrjIscity(String cwrPrjIscity) {
        this.cwrPrjIscity = cwrPrjIscity == null ? null : cwrPrjIscity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_istown
     *
     * @return the value of cwr_project.cwr_prj_istown
     *
     * @mbg.generated
     */
    public String getCwrPrjIstown() {
        return cwrPrjIstown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_istown
     *
     * @param cwrPrjIstown the value for cwr_project.cwr_prj_istown
     *
     * @mbg.generated
     */
    public void setCwrPrjIstown(String cwrPrjIstown) {
        this.cwrPrjIstown = cwrPrjIstown == null ? null : cwrPrjIstown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_red_area
     *
     * @return the value of cwr_project.cwr_red_area
     *
     * @mbg.generated
     */
    public BigDecimal getCwrRedArea() {
        return cwrRedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_red_area
     *
     * @param cwrRedArea the value for cwr_project.cwr_red_area
     *
     * @mbg.generated
     */
    public void setCwrRedArea(BigDecimal cwrRedArea) {
        this.cwrRedArea = cwrRedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prj_scan
     *
     * @return the value of cwr_project.cwr_prj_scan
     *
     * @mbg.generated
     */
    public String getCwrPrjScan() {
        return cwrPrjScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prj_scan
     *
     * @param cwrPrjScan the value for cwr_project.cwr_prj_scan
     *
     * @mbg.generated
     */
    public void setCwrPrjScan(String cwrPrjScan) {
        this.cwrPrjScan = cwrPrjScan == null ? null : cwrPrjScan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_subject_id
     *
     * @return the value of cwr_project.cwr_subject_id
     *
     * @mbg.generated
     */
    public String getCwrSubjectId() {
        return cwrSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_subject_id
     *
     * @param cwrSubjectId the value for cwr_project.cwr_subject_id
     *
     * @mbg.generated
     */
    public void setCwrSubjectId(String cwrSubjectId) {
        this.cwrSubjectId = cwrSubjectId == null ? null : cwrSubjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_subject_code
     *
     * @return the value of cwr_project.cwr_subject_code
     *
     * @mbg.generated
     */
    public String getCwrSubjectCode() {
        return cwrSubjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_subject_code
     *
     * @param cwrSubjectCode the value for cwr_project.cwr_subject_code
     *
     * @mbg.generated
     */
    public void setCwrSubjectCode(String cwrSubjectCode) {
        this.cwrSubjectCode = cwrSubjectCode == null ? null : cwrSubjectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_supervisor
     *
     * @return the value of cwr_project.cwr_supervisor
     *
     * @mbg.generated
     */
    public String getCwrSupervisor() {
        return cwrSupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_supervisor
     *
     * @param cwrSupervisor the value for cwr_project.cwr_supervisor
     *
     * @mbg.generated
     */
    public void setCwrSupervisor(String cwrSupervisor) {
        this.cwrSupervisor = cwrSupervisor == null ? null : cwrSupervisor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_supv_group
     *
     * @return the value of cwr_project.cwr_supv_group
     *
     * @mbg.generated
     */
    public String getCwrSupvGroup() {
        return cwrSupvGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_supv_group
     *
     * @param cwrSupvGroup the value for cwr_project.cwr_supv_group
     *
     * @mbg.generated
     */
    public void setCwrSupvGroup(String cwrSupvGroup) {
        this.cwrSupvGroup = cwrSupvGroup == null ? null : cwrSupvGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_prv_prj_code
     *
     * @return the value of cwr_project.cwr_prv_prj_code
     *
     * @mbg.generated
     */
    public String getCwrPrvPrjCode() {
        return cwrPrvPrjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_prv_prj_code
     *
     * @param cwrPrvPrjCode the value for cwr_project.cwr_prv_prj_code
     *
     * @mbg.generated
     */
    public void setCwrPrvPrjCode(String cwrPrvPrjCode) {
        this.cwrPrvPrjCode = cwrPrvPrjCode == null ? null : cwrPrvPrjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_sg_comid
     *
     * @return the value of cwr_project.cwr_sg_comid
     *
     * @mbg.generated
     */
    public String getCwrSgComid() {
        return cwrSgComid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_sg_comid
     *
     * @param cwrSgComid the value for cwr_project.cwr_sg_comid
     *
     * @mbg.generated
     */
    public void setCwrSgComid(String cwrSgComid) {
        this.cwrSgComid = cwrSgComid == null ? null : cwrSgComid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cwr_project.cwr_cmpl_date
     *
     * @return the value of cwr_project.cwr_cmpl_date
     *
     * @mbg.generated
     */
    public Date getCwrCmplDate() {
        return cwrCmplDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cwr_project.cwr_cmpl_date
     *
     * @param cwrCmplDate the value for cwr_project.cwr_cmpl_date
     *
     * @mbg.generated
     */
    public void setCwrCmplDate(Date cwrCmplDate) {
        this.cwrCmplDate = cwrCmplDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cwr_project
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eafId=").append(eafId);
        sb.append(", eafCreator=").append(eafCreator);
        sb.append(", eafModifytime=").append(eafModifytime);
        sb.append(", eafCreatetime=").append(eafCreatetime);
        sb.append(", eafModifier=").append(eafModifier);
        sb.append(", cwrPrjName=").append(cwrPrjName);
        sb.append(", cwrPrjJian=").append(cwrPrjJian);
        sb.append(", cwrPrjMan=").append(cwrPrjMan);
        sb.append(", cwrPrjDes=").append(cwrPrjDes);
        sb.append(", cwrPrjAddr=").append(cwrPrjAddr);
        sb.append(", cwrPrjStatus=").append(cwrPrjStatus);
        sb.append(", cwrOrgName=").append(cwrOrgName);
        sb.append(", cwrOrgJian=").append(cwrOrgJian);
        sb.append(", cwrPrjDir=").append(cwrPrjDir);
        sb.append(", cwrCostEng=").append(cwrCostEng);
        sb.append(", cwrPreEng=").append(cwrPreEng);
        sb.append(", cwrProEng=").append(cwrProEng);
        sb.append(", cwrFgpfCode=").append(cwrFgpfCode);
        sb.append(", cwrPrjType=").append(cwrPrjType);
        sb.append(", cwrRecYear=").append(cwrRecYear);
        sb.append(", cwrMajCat=").append(cwrMajCat);
        sb.append(", cwrTotalArea=").append(cwrTotalArea);
        sb.append(", cwrKspfLx=").append(cwrKspfLx);
        sb.append(", cwrGspfDy=").append(cwrGspfDy);
        sb.append(", cwrPfgsTz=").append(cwrPfgsTz);
        sb.append(", cwrAppCode=").append(cwrAppCode);
        sb.append(", cwrGcghxkCode=").append(cwrGcghxkCode);
        sb.append(", cwrYdghxkCode=").append(cwrYdghxkCode);
        sb.append(", cwrXzyjsCode=").append(cwrXzyjsCode);
        sb.append(", cwrConCode=").append(cwrConCode);
        sb.append(", cwrStartDate=").append(cwrStartDate);
        sb.append(", cwrPrjStage=").append(cwrPrjStage);
        sb.append(", cwrPrjCode=").append(cwrPrjCode);
        sb.append(", cwrUseCom=").append(cwrUseCom);
        sb.append(", cwrCapFrom=").append(cwrCapFrom);
        sb.append(", cwrSupUnit=").append(cwrSupUnit);
        sb.append(", cwrPrjView=").append(cwrPrjView);
        sb.append(", cwrJdbh=").append(cwrJdbh);
        sb.append(", cwrPrjArea=").append(cwrPrjArea);
        sb.append(", cwrPrjPhoto=").append(cwrPrjPhoto);
        sb.append(", cwrAddrJd=").append(cwrAddrJd);
        sb.append(", cwrAddrWd=").append(cwrAddrWd);
        sb.append(", cwrIsvproj=").append(cwrIsvproj);
        sb.append(", cwrSgUnit=").append(cwrSgUnit);
        sb.append(", cwrPrjGcbh=").append(cwrPrjGcbh);
        sb.append(", cwrPrjIslinked=").append(cwrPrjIslinked);
        sb.append(", cwrPrjIssalary=").append(cwrPrjIssalary);
        sb.append(", cwrJsUnit=").append(cwrJsUnit);
        sb.append(", cwrLinkedDate=").append(cwrLinkedDate);
        sb.append(", cwrSalaryDate=").append(cwrSalaryDate);
        sb.append(", cwrStorageGold=").append(cwrStorageGold);
        sb.append(", cwrControlUnit=").append(cwrControlUnit);
        sb.append(", cwrDesignUnit=").append(cwrDesignUnit);
        sb.append(", cwrQualityUnit=").append(cwrQualityUnit);
        sb.append(", cwrSafetyUnit=").append(cwrSafetyUnit);
        sb.append(", cwrPaAddr=").append(cwrPaAddr);
        sb.append(", cwrPrjIsbegin=").append(cwrPrjIsbegin);
        sb.append(", cwrEnginName=").append(cwrEnginName);
        sb.append(", cwrEnginAddr=").append(cwrEnginAddr);
        sb.append(", cwrPrjIscity=").append(cwrPrjIscity);
        sb.append(", cwrPrjIstown=").append(cwrPrjIstown);
        sb.append(", cwrRedArea=").append(cwrRedArea);
        sb.append(", cwrPrjScan=").append(cwrPrjScan);
        sb.append(", cwrSubjectId=").append(cwrSubjectId);
        sb.append(", cwrSubjectCode=").append(cwrSubjectCode);
        sb.append(", cwrSupervisor=").append(cwrSupervisor);
        sb.append(", cwrSupvGroup=").append(cwrSupvGroup);
        sb.append(", cwrPrvPrjCode=").append(cwrPrvPrjCode);
        sb.append(", cwrSgComid=").append(cwrSgComid);
        sb.append(", cwrCmplDate=").append(cwrCmplDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}